services:
  restapi-server:
    build:
      context: Streamario_web_backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    container_name: restapi-server
    env_file:
      - Streamario_web_backend/.env

  unityws-server:
    build:
      context: Streamario_web_backend
      dockerfile: Dockerfile.unityws
    ports:
      - "8890:8890"
    container_name: unityws-server
    env_file:
      - Streamario_web_backend/.env


  # ローカルdbを使いたい場合は以下を復活させてください
  # db:
  #   image: postgres:16-alpine
  #   ports:
  #     - "5432:5432"
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: streamario
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
  #   volumes:
  #     - ./db/postgres_data:/var/lib/postgresql/data
  #     - ./Streamario_web_backend/db/migrations:/docker-entrypoint-initdb.d
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d streamario"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s

  # ローカルRedisを使いたい場合は以下を復活させてください
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   container_name: redis
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - ./db/redis_data:/data
